title: "Σ Sigma"
description: "Cours, exercices, devoirs et corrigés"
url: "https://ibrahim-rudasingwa.fr"
theme: null

markdown: kramdown

school_name: "Lycée Younoussa Bamana"
school_address: "-"
school_city: "Mamoudzou, Mayotte"

contact_name: "Ibrahim Rudasingwa"
contact_email: "brhmrudasingwa@gmail.com"
